version: 2

jobs:
  build:
    docker:
      - image: docker:stable-dind

    working_directory: /practice-circleci

    parallelism: 1

    steps:
      - run:
          command: |
            apk add --no-cache curl git openssh

      - checkout

      - setup_remote_docker

      - run:
          command: |
            curl -o /usr/local/bin/circleci https://circle-downloads.s3.amazonaws.com/releases/build_agent_wrapper/circleci
            chmod +x /usr/local/bin/circleci
            circleci version

      - run:
          command: |
            mkdir test
            echo "$(date) - test-1" > test/test-1-test.target
            echo "$(date) - test-2" > test/test-2-test.target

      - run:
          command: |
            ##circleci tests glob "test/*-test.target" | xargs -n 1 echo
            TESTFILES=$(circleci tests glob "test/*-test.target" | circleci tests split --split-by=timings)
            echo ${TESTFILES}
  