version: 2

jobs:
  build:
    # The resource classes are as follows:
    # small: 1CPU and 1RAM
    # medium: 2CPU and 4RAM (current 1.0 default)
    # large: 4CPU and 8RAM
    ##resource_class: large

    docker:
      - image: n0ts/docker-circleci
        user: docker

    environment:
      - CI: true

    working_directory: /work/practice-circleci

    parallelism: 2

    steps:
      - checkout

  test1:
    working_directory: /work/practice-circleci

    docker:
      - image: n0ts/docker

    steps:
      - run:
          name: Run test 1
          command: |
            echo "Run test1 - $(date)"
            sleep 5
            echo "Done test1 - $(date)"

  test2:
    docker:
      - image: n0ts/ubuntu

    working_directory: /work/practice-circleci

    steps:
      - run:
          name: Run test 2
          command: |
            echo "Run test2 - $(date)"
            sleep 10
            echo "Done test2 - $(date)"

  deploy:
    docker:
      - image: n0ts/ubuntu-java

    working_directory: /work/practice-circleci

    steps:
      - run:
          name: Deploy
          command: |
            echo "Deploy - $(date)"

workflows:
  version: 2

  build-and-test:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - build
      - deploy:
          requires:
            - test1
            - test2
