version: 2

jobs:
  build:
    # The resource classes are as follows:
    # small: 1CPU and 1RAM
    # medium: 2CPU and 4RAM (current 1.0 default)
    # large: 4CPU and 8RAM
    ##resource_class: large

    docker:
      - image: n0ts/docker-circleci
        user: docker

    environment:
      - CI: true
      # - MYSQL_DATABASE: test
      # - MYSQL_USER: test_user
      # - MYSQL_PASSWORD: testpw

    working_directory: /work/practice-circleci

    parallelism: 1

    steps:
      - checkout

    test1:
      docker:
        - image: n0ts/docker

      steps:
        - name: Run test1
          command: |
            echo "Run test1"
            sleep 30
            echo "Done test1"

    test2:
      steps:
        - name: Run tes2
          command: |
            echo "Run test2"
            sleep 60
            echo "Done test2"

    deploy:
      steps:
        - name: Deploy
          command: |
            echo "Deploy"

workflows:
  version: 2

  build-and-test:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - test1
      - deploy:
          requires:
            - test2
