version: 2

# https://circleci.com/gh/teppeis-sandbox/circleci-multiple-versions/27#config/containers/0
jobs:
  build:
    docker:
      - image: n0ts/docker-circleci
        user: docker

    working_directory: /work/practice-circleci

    steps:
      - checkout

      - run:
          name: Trigger Jobs
          command: |
            function trigger_job() {
              job_name=$1
              curl -X POST -H "Content-Type: application/json" \
                  -f \
                  -d "{
                      \"build_parameters\": {
                        \"CIRCLE_JOB\": \"$job_name\"
                      },
                      \"revision\": \"$CIRCLE_SHA1\"
                    }" \
                  https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH?circle-token=$CIRCLE_API_TOKEN
            }
            trigger_job build-test-1
            trigger_job build-test-2
            trigger_job build-test-3

  build-common: &common-build
    docker:
      - image: n0ts/ubuntu

    environment:
      BAR: foo

    working_directory: /work

    steps:
      - run:
          name: Test common
          command: |
            ls -l /work
            echo $FOO
            echo $BAR

  build-test-1:
    <<: *common-build
    docker:
      - image: n0ts/ubuntu-java

    environment:
      TEST1: true

  steps:
      - run:
          name: Test 1
          command: |
            echo "Test 1"
            java -version

  build-test-2:
    <<: *common-build
    docker:
      - image: n0ts/ubuntu-python

    steps:
      - run:
          name: Test 2
          command: |
            echo "Test 2"
            python --version

  build-test-3:
    <<: *common-build

    environment:
      FOO: bar